/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static Clases.Cliente.reloj;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias
 */

//Esta clase es la interfaz principal del cliente, donde se va a ir mostrando y actualizando la ultima parada del bus que escogimos
public final class EstadoBus extends javax.swing.JFrame {

    String lastParada;
    String bus;
    Date fecha = new Date();

    public String getLastParada() {
        return lastParada;
    }

    public void setLastParada(String lastParada) {
        this.lastParada = lastParada;
    }

    /**
     * Creates new form EstadoBus
     *
     * @param buss
     */
    public EstadoBus(String buss) {//recibe el bus que se está monitoreando 

        initComponents();
        bus = buss;
        reloj.setLabelHora(label_hora);//le asigna un label al reloj para poder imprimir la hora
        infotxt.setEditable(false);
        start();
    }

    private void start() {
        infotxt.setText("Día: " + fecha + "\nEscogiste el bus: " + bus + "\n\n Última Parada: \n");
    }

    public void recorrido(String lastParada) {//actualiza e imprime la ultima parada del bus

        if (reloj.isFin()) {
            this.dispose();
        }
        infotxt.setText(infotxt.getText() + lastParada + ", Hora: " + reloj.toString() + "\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infotxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt_info = new javax.swing.JButton();
        bt_horario = new javax.swing.JButton();
        bt_paradas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado del Bus");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        infotxt.setColumns(20);
        infotxt.setRows(5);
        jScrollPane1.setViewportView(infotxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 470, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        label_hora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(label_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 110, 47));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/humo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/reloj.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 16, 58, -1));

        bt_info.setText("Información");
        bt_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_infoActionPerformed(evt);
            }
        });
        jPanel1.add(bt_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        bt_horario.setText("Horarios");
        bt_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_horarioActionPerformed(evt);
            }
        });
        jPanel1.add(bt_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        bt_paradas.setText("Paradas");
        bt_paradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_paradasActionPerformed(evt);
            }
        });
        jPanel1.add(bt_paradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/busespattern.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Presionar este botón nos brindará información sobre los horarios
    private void bt_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_horarioActionPerformed
        JOptionPane.showMessageDialog(rootPane, "El servicio de buses trabaja de 5:00 am a 12:00 pm\n"
                + "Los domingos el horario es de 5:00 am a 7:00 pm", "Horarios", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_bt_horarioActionPerformed
//Presionar este botón nos brindará información sobre las paradas
    private void bt_paradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_paradasActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("paradas.png"));
        JOptionPane.showMessageDialog(rootPane, "", "Info sobre las paradas", JOptionPane.PLAIN_MESSAGE, icono);
    }//GEN-LAST:event_bt_paradasActionPerformed

    //Presionar este botón nos brindará información general del programa
    private void bt_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_infoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "El programa irá imprimiendo la última parada del bus que escogiste"
                + " hasta las 24:00 mn que terminará su ejecución\n"
                + "", "Información General", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_bt_infoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_horario;
    private javax.swing.JButton bt_info;
    private javax.swing.JButton bt_paradas;
    private javax.swing.JTextArea infotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_hora;
    // End of variables declaration//GEN-END:variables

}
