
package Interfaz;

/**
 *
 * @author Elias
 */

//Ventana de bienvenida al programa, aquí eligiremos el bus que deseamos monitorear
public class SeleccionBus extends javax.swing.JFrame {

    String bus = null;

    public SeleccionBus() {

        this.bus = null;
        initComponents();
    }

    public String getBus() {
        return bus;
    }

    public void setBus(String bus) {
        this.bus = bus;
    }

    /**
     * Creates new form SeleccionBus
     * @param num
     */
    public void next(String num) {//recibe el numero del bus escojido

        bus = num;
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bt_bus1 = new javax.swing.JButton();
        bt_bus2 = new javax.swing.JButton();
        bt_bus3 = new javax.swing.JButton();
        bt_bus4 = new javax.swing.JButton();
        bt_bus5 = new javax.swing.JButton();
        bt_bus6 = new javax.swing.JButton();
        bt_bus7 = new javax.swing.JButton();
        bt_bus8 = new javax.swing.JButton();
        bt_bus9 = new javax.swing.JButton();
        bt_bus10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo.setBackground(new java.awt.Color(0, 0, 0));
        label_titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setText("Seleccionar Bus");
        jPanel1.add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 12, 210, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione el autobus que desea monitorear");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 80, -1, -1));

        bt_bus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 147, -1, -1));

        bt_bus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 239, -1, -1));

        bt_bus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 342, -1, -1));

        bt_bus4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 342, -1, -1));

        bt_bus5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus5, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 443, -1, -1));

        bt_bus6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus6, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 147, -1, -1));

        bt_bus7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus7, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 147, -1, -1));

        bt_bus8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus8, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 239, -1, -1));

        bt_bus9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus9, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 239, -1, -1));

        bt_bus10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/bus.png"))); // NOI18N
        bt_bus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bus10ActionPerformed(evt);
            }
        });
        jPanel1.add(bt_bus10, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 342, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 177, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("4");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 264, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("7");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 367, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("8");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 364, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 263, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 176, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("3");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 175, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("6");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 269, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("9");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("10");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 467, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaz/fondoc.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 530, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_bus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus1ActionPerformed
next("1");    }//GEN-LAST:event_bt_bus1ActionPerformed

    private void bt_bus6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus6ActionPerformed
next("2");    }//GEN-LAST:event_bt_bus6ActionPerformed

    private void bt_bus7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus7ActionPerformed
next("3");    }//GEN-LAST:event_bt_bus7ActionPerformed

    private void bt_bus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus2ActionPerformed
next("4");    }//GEN-LAST:event_bt_bus2ActionPerformed

    private void bt_bus8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus8ActionPerformed
next("5");    }//GEN-LAST:event_bt_bus8ActionPerformed

    private void bt_bus9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus9ActionPerformed
next("6");    }//GEN-LAST:event_bt_bus9ActionPerformed

    private void bt_bus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus3ActionPerformed
next("7");    }//GEN-LAST:event_bt_bus3ActionPerformed

    private void bt_bus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus4ActionPerformed
next("8");    }//GEN-LAST:event_bt_bus4ActionPerformed

    private void bt_bus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus10ActionPerformed
next("9");    }//GEN-LAST:event_bt_bus10ActionPerformed

    private void bt_bus5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bus5ActionPerformed
       next("10"); // TODO add your handling code here:
    }//GEN-LAST:event_bt_bus5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_bus1;
    private javax.swing.JButton bt_bus10;
    private javax.swing.JButton bt_bus2;
    private javax.swing.JButton bt_bus3;
    private javax.swing.JButton bt_bus4;
    private javax.swing.JButton bt_bus5;
    private javax.swing.JButton bt_bus6;
    private javax.swing.JButton bt_bus7;
    private javax.swing.JButton bt_bus8;
    private javax.swing.JButton bt_bus9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_titulo;
    // End of variables declaration//GEN-END:variables
}
